#!/usr/bin/env python3
import subprocess
import sys
import os
import trust_boundary.errors
import trust_boundary.scan


def main():
    if len(sys.argv) != 2:
        raise RuntimeError("Expected path to commit message file!")
    commit_msg_file = sys.argv[1]
    with open(commit_msg_file, "r") as f:
        message = f.read()

    scanner = trust_boundary.scan.Scanner()
    scanner.scan_string(context="CommitMessage", value=message)
    if scanner.detections:
        print(f"Detection of {len(scanner.detections)} bad symbol(s)!")
        scanner.display_detections()
        raise trust_boundary.errors.ExitWithMessageError("Bad symbols detected!")


if __name__ == "__main__":
    try:
        main()
    except trust_boundary.errors.ExitWithMessageError as e:
        e.display()
        sys.exit(-1)
